version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\src
# Do not build on tags
skip_tags: true
init:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "echo MSYSTEM=%MSYSTEM% > /appveyor.environment"
environment:
  matrix:
  - MSYSTEM: MINGW32
  - MSYSTEM: MINGW64
install:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "cd /c/projects/src/share && ./appveyor-install.sh"

build_script:
- cmd: c:\msys64\usr\bin\bash -lc "cd /c/projects/src/share && ./appveyor-build.sh"

deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  auth_token:
    secure: sZu+i3QuPeW93JlxEBOJ7E1WYsAZQtIsOHVjzftLxkBvBKX/9Akt4GRYUdQWK3/Z
  artifact: goffice
  draft: false
  prerelease: true
  on:
      branch:
        - msys2
